# # Use Node.js 20.15.0 base image
FROM node:20.15.0-alpine

# # Set working directory
# WORKDIR /app

# # Copy package.json and package-lock.json
# COPY package*.json ./
# COPY yarn.lock ./
# COPY prisma ./prisma/

# # Install dependencies
# RUN yarn cache clean
# RUN yarn install --legacy-peer-deps

# # Copy the rest of the application code
# COPY . .

# # Generate Prisma Client code
# RUN yarn generate

# # Expose the port the app runs on, here, I was using port 3333
# EXPOSE 3333

# # Command to run the app
# CMD [ "yarn", "dev", "start:migrate:prod" ]
